---
title: "Viz 3D meteorite landings"
output: html_document
date: "2025-02-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
meteorite <- read.csv("/Users/yannis/Desktop/Projet tutoré/Meteorite_Landings.csv")
```

```{r}
library(threejs)
```
```{r}
earth <- "http://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73909/world.topo.bathy.200412.3x5400x2700.jpg"
```

m
```{r}
meteorite_clean <- na.omit(meteorite)
meteorite_clean <- meteorite_clean[meteorite_clean$year != 860,]
```

On clean les données et on lance une app shiny :
```{r}
library(shiny)
library(shinyjs)
library(dplyr)
library(geojsonio)
library(threejs)
library(sf)
library(shinydashboard)

countries <- read_sf('/Users/yannis/Desktop/Projet tutoré/countries.geojson')
meteorite_clean <- meteorite_clean[!is.na(meteorite_clean$year) & meteorite_clean$year >= 1900 & meteorite_clean$year <= 2013, ]

ui <- dashboardPage(
  dashboardHeader(title = "Visualisation des Météorites"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Filtres", tabName = "filters", icon = icon("filter")),
      menuItem("Carte", tabName = "map", icon = icon("globe"))
    )
  ),
  dashboardBody(
    useShinyjs(),
    tabItems(
      tabItem(tabName = "filters",
              h3("Filtres"),
              sliderInput("year_range", 
                          "Sélectionnez l'intervalle d'années :", 
                          min = 1900, 
                          max = 2013, 
                          value = c(1900, 2013), 
                          step = 10),
              selectInput("weight_category", 
                          "Choisissez une catégorie de poids :", 
                          choices = c("Tous les poids", unique(meteorite_clean$weight_category)),
                          selected = "Tous les poids"),
              selectInput("mass_category", 
                          "Choisissez une plage de masse :", 
                          choices = c("Toutes les masses", 
                                      "0 - 10g", "10 - 100g", "100g - 1kg", 
                                      "1kg - 10kg", "10kg - 100kg", "100kg - 1T", 
                                      "1T - 10T", "10T - 100T"),
                          selected = "Toutes les masses"),
              actionButton("play", "Play", class = "btn")
      ),
      tabItem(tabName = "map",
              uiOutput("globe"),
              textOutput("meteorite_count")
      )
    )
  )
)

server <- function(input, output, session) {
  
  filtered_data <- reactive({
      data <- meteorite_clean[meteorite_clean$year >= input$year_range[1] & meteorite_clean$year <= input$year_range[2], ]
      
      if (input$weight_category != "Tous les poids") {
          data <- subset(data, weight_category == input$weight_category)
      }
      
      if (input$mass_category != "Toutes les masses") {
          mass_ranges <- list(
              "0 - 10g" = c(0, 10),
              "10 - 100g" = c(10, 100),
              "100g - 1kg" = c(100, 1000),
              "1kg - 10kg" = c(1000, 10000),
              "10kg - 100kg" = c(10000, 100000),
              "100kg - 1T" = c(100000, 1000000),
              "1T - 10T" = c(1000000, 10000000),
              "10T - 100T" = c(10000000, 100000000)
          )
          range <- mass_ranges[[input$mass_category]]
          data <- subset(data, mass..g. >= range[1] & mass..g. <= range[2])
      }
      
      return(data)
  })

  output$globe <- renderUI({
      data <- filtered_data()
      colors <- ifelse(data$mass..g. > 1000, "red", "green")
      
      globejs(
          img = earth,
          lat = data$reclat, 
          long = data$reclong, 
          color = colors, 
          arcsHeight = 0.3, 
          pointsize = 1, 
          atmosphere = TRUE,
          geojson = countries,
          onClick = "function(event) {
              if (event.properties && event.properties.name) {
                  var countryName = event.properties.name; 
                  alert('Vous avez cliqué sur ' + countryName);
              }
          }",
          onHover = "function(event) {
              if (event.properties && event.properties.name) {
                  return event.properties.name; 
              }
          }"
      )
  })

  output$meteorite_count <- renderText({
      count <- nrow(filtered_data())
      paste("Nombre de météorites :", count)  
  })
}

shinyApp(ui = ui, server = server)

```
Objectif : Faire un dashboard dans ce style :
https://github.com/sebkl/globejs/blob/master/README.md


```{r}
library(shiny)
library(shinyjs)
library(dplyr)
library(geojsonio)
library(threejs)
library(sf)
library(shinydashboard)




ui <- dashboardPage(
  dashboardHeader(title = "Visualisation des Météorites"),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Filtres", tabName = "filters", icon = icon("filter")),
      menuItem("Carte", tabName = "map", icon = icon("globe"))
    )
  ),
  dashboardBody(
    useShinyjs(),
    tags$head(
      tags$style(HTML("
        body {
          background-color: #e0e0e0;
        }
        .content {
          background-color: #f4f4f4;
          border-radius: 8px;
          padding: 20px;
        }
        .sidebar {
          background-color: #3c8dbc;
          color: white;
        }
        .btn {
          background-color: #007bff;
          color: white;
          border-radius: 5px;
        }
        .btn:hover {
          background-color: #0056b3;
        }
        .tooltip {
          position: absolute;
          text-align: center;
          padding: 5px;
          background-color: rgba(0, 0, 0, 0.7);
          color: white;
          border-radius: 5px;
          visibility: hidden;
          z-index: 1000; /* Pour s'assurer que l'info-bulle est au-dessus des autres éléments */
        }
      "))
    ),
    div(class = "tooltip", id = "tooltip"),
    tabItems(
      tabItem(tabName = "filters",
              h3("Filtres"),
              radioButtons("filter_type", 
                           "Choisissez le type de filtrage :", 
                           choices = list("Par décennie" = "decade", "Toutes les années" = "all"), 
                           selected = "decade"),
              conditionalPanel(
                condition = "input.filter_type == 'decade'",
                sliderInput("decade", 
                            "Sélectionnez la décennie :", 
                            min = min(meteorite_clean$decade), 
                            max = max(meteorite_clean$decade), 
                            value = min(meteorite_clean$decade), 
                            step = 10)
              ),
              selectInput("weight_category", 
                          "Choisissez une catégorie de poids :", 
                          choices = c("Tous les poids", unique(meteorite_clean$weight_category)),
                          selected = "Tous les poids"),
              actionButton("play", "Play", class = "btn")
      ),
      tabItem(tabName = "map",
              uiOutput("globe"),
              textOutput("meteorite_count")
      )
    )
  )
)

server <- function(input, output, session) {
  

  filtered_data <- reactive({
    if (input$filter_type == "all") {
      return(meteorite_clean)
    } else {
      data <- subset(meteorite_clean, decade == input$decade)
      if (input$weight_category != "Tous les poids") {
        data <- subset(data, weight_category == input$weight_category)
      }
      return(data)
    }
  })
  
  output$globe <- renderUI({
    data <- filtered_data()
    colors <- ifelse(data$mass..g. > 1000, "red", "green")
    
    globejs(
      img = earth,  
      lat = data$reclat, 
      long = data$reclong, 
      color = colors, 
      arcsHeight = 0.3, 
      pointsize = 1, 
      atmosphere = TRUE,
      geojson = countries_geojson,
      onClick = "function(event) {
        if (event.properties && event.properties.name) {
          var countryName = event.properties.name; 
          alert('Vous avez cliqué sur ' + countryName);
        }
      }"
    )
  })
  

  outputOptions(output, "globe", suspendWhenHidden = FALSE)
  
  observe({
    shinyjs::runjs("
      var tooltip = document.getElementById('tooltip');
      var globe = document.querySelector('.threejs');
      
      globe.addEventListener('mousemove', function(event) {
        var country = event.target;
        if (country && country.properties && country.properties.name) {
          tooltip.style.visibility = 'visible';
          tooltip.innerHTML = country.properties.name;
          tooltip.style.left = event.clientX + 'px';
          tooltip.style.top = (event.clientY - 30) + 'px'; // Ajuste la position
        } else {
          tooltip.style.visibility = 'hidden';
        }
      });
    ")
  })
  
  output$meteorite_count <- renderText({
    count <- nrow(filtered_data())
    paste("Nombre de météorites :", count)  
  })
}

shinyApp(ui = ui, server = server)

```


